### ISSUE TITLE
Broken URL: Plugin development

### ISSUE THREAD

**Issue by csteinmetz1** [okio-ai/nendo#2]
Very cool project! 

I am curious to learn more about developing plugins for nendo, but the [URL](https://okio.ai/docs/development/pluginsdev/) at the end of the README gives a 404.

**Comment by faradox** [comment]
Nice catch! That's a typo in the link, will fix right away. Meanwhile, [this is the correct URL to the plugin development documentation](https://okio.ai/docs/development/plugindev/).

Thanks for letting us know.
