### ISSUE TITLE
various Issues running example on main page

### ISSUE THREAD

**Issue by gijzelaerr** [okio-ai/nendo#6]
If I run the example on your main page:

```
$ pip install nendo
$ pip install nendo-plugin-musicgen
```

I run into issues since the wheel doesn't support Python 3.11.

If I create a virtual env with Python 3.10 and continue I run into issues since PostgreSQL is not installed. I don't know why PostgreSQL is required, you can also consider depending on psycopg2-binary or make the PostgreSQL dep optional. 

After installing PostgreSQL, the next error I get is `Failed to import plugin 'nendo_plugin_musicgen'. Error: No module named 'audiocraft'`.

If I try to pip install audiocraft I get an error that torch is not installed.

According to the torch website to install torch on my osx m1 I should install  the packages torch torchvision torchaudio, but then still audiocraft installing fails:

`ModuleNotFoundError: No module named 'torch'`

**Comment by faradox** [comment]
Thank you for submitting this. We updated the README of nendo core and the nendo musicgen plugin to better the requirements for running the example and how to fulfill them on Mac OSX. Have fun using nendo and let us know if you encounter any other issues.

**Comment by gijzelaerr** [comment]
great, thanks!
